In [ ]:
###############################################
# PYTHON İLE VERİ ANALİZİ (DATA ANALYSIS WITH PYTHON)
###############################################
# - NumPy
# - Pandas
# - Veri Görselleştirme: Matplotlib & Seaborn
# - Gelişmiş Fonksiyonel Keşifçi Veri Analizi (Advanced Functional Exploratory Data Analysis)

#############################################
# NUMPY
#############################################

# Neden NumPy? (Why Numpy?)
# NumPy Array'i Oluşturmak (Creating Numpy Arrays)
# NumPy Array Özellikleri (Attibutes of Numpy Arrays)
# Yeniden Şekillendirme (Reshaping)
# Index Seçimi (Index Selection)
# Slicing
# Fancy Index
# Numpy'da Koşullu İşlemler (Conditions on Numpy)
# Matematiksel İşlemler (Mathematical Operations)

In [ ]:
#############################################
# Neden NumPy?
#############################################
import numpy as np
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

ab = []

for i in range(0, len(a)):
    ab.append(a[i] * b[i])

a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a * b


In [ ]:
#############################################
# NumPy Array'i Oluşturmak (Creating Numpy Arrays)
#############################################
import numpy as np

np.array([1, 2, 3, 4, 5])
type(np.array([1, 2, 3, 4, 5]))
np.zeros(10, dtype=int)
np.random.randint(0, 10, size=10)
np.random.normal(10, 4, (3, 4))

In [ ]:
type(np.array([1, 2, 3, 4, 5]))

In [ ]:
np.zeros(10, dtype=int)

In [ ]:
np.random.randint(0, 10, size=10)

In [ ]:
np.random.normal(10, 4, (3, 4))

In [ ]:
#############################################
# NumPy Array Özellikleri (Attibutes of Numpy Arrays)
#############################################
import numpy as np

# ndim: boyut sayısı
# shape: boyut bilgisi
# size: toplam eleman sayısı
# dtype: array veri tipi

a = np.random.randint(10, size=5)
a.ndim
a.shape
a.size
a.dtype


In [ ]:
a

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a.dtype

In [ ]:
#############################################
# Yeniden Şekillendirme (Reshaping)
#############################################
import numpy as np

np.random.randint(1, 10, size=9)
np.random.randint(1, 10, size=9).reshape(3, 3)

ar = np.random.randint(1, 10, size=9)
ar.reshape(3, 3)

In [ ]:
np.random.randint(1, 10, size=9)

In [ ]:
np.random.randint(1, 10, size=9).reshape(3, 3)

In [ ]:
ar = np.random.randint(1, 10, size=9)
ar.reshape(3, 3)

In [ ]:
#############################################
# Index Seçimi (Index Selection)
#############################################
import numpy as np
a = np.random.randint(10, size=10)
a[0]
a[0:5]
a[0] = 999

m = np.random.randint(10, size=(3, 5))

m[0, 0]
m[1, 1]
m[2, 3]

m[2, 3] = 999

m[2, 3] = 2.9

m[:, 0]
m[1, :]
m[0:2, 0:3]

In [ ]:
a = np.random.randint(10, size=10)
a

In [ ]:
a[0]

In [ ]:
a[0:5]

In [ ]:
a[0] = 999
a

In [ ]:
m = np.random.randint(10, size=(3, 5))
m

In [ ]:
#############################################
# Fancy Index
#############################################
import numpy as np

v = np.arange(0, 30, 3)
v[1]
v[4]

catch = [1, 2, 3]

v[catch]


In [ ]:
v = np.arange(0, 30, 3)
v


In [ ]:
v[1]

In [ ]:
catch = [1, 2, 4]

v[catch]

In [ ]:
#############################################
# Numpy'da Koşullu İşlemler (Conditions on Numpy)
#############################################
import numpy as np
v = np.array([1, 2, 3, 4, 5])

#######################
# Klasik döngü ile
#######################
ab = []
for i in v:
    if i < 4:
        ab.append(i)
ab

In [ ]:
#######################
# Numpy ile
#######################
v < 3

v[v < 3]
v[v > 3]
v[v != 3]
v[v == 3]
v[v >= 3]


In [ ]:
v < 3

In [ ]:
v[v < 3]

In [ ]:
v[v != 3]

In [ ]:
v[v == 3]

In [65]:
#############################################
# Matematiksel İşlemler (Mathematical Operations)
#############################################
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [66]:
v

array([1, 2, 3, 4, 5])

In [67]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [68]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [69]:
v - 1

array([0, 1, 2, 3, 4])

In [78]:
np.subtract(v, 1)


array([-4, -3, -2, -1,  0])

In [79]:
np.add(v, 1)


array([-2, -1,  0,  1,  2])

In [95]:
np.mean(v)


-2.0

In [88]:
np.sum(v)


-10

In [89]:
np.min(v)


-4

In [90]:
np.max(v)

0

In [93]:
v

array([-4, -3, -2, -1,  0])

In [94]:
np.var(v) #var= mean(abs(x-x.mean())^2)

2.0

In [85]:
v = np.subtract(v, 1)
v

array([-4, -3, -2, -1,  0])

In [96]:
#######################
# NumPy ile İki Bilinmeyenli Denklem Çözümü
#######################

# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])

np.linalg.solve(a, b)

array([1.85714286, 2.71428571])